global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "exchange-gateway"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: /metrics

  - job_name: "exchange-order"
    static_configs:
      - targets: ["host.docker.internal:8081"]
    metrics_path: /metrics

  - job_name: "exchange-matching"
    static_configs:
      - targets: ["host.docker.internal:8082"]
    metrics_path: /metrics

  - job_name: "exchange-clearing"
    static_configs:
      - targets: ["host.docker.internal:8083"]
    metrics_path: /metrics

  - job_name: "exchange-marketdata"
    static_configs:
      - targets: ["host.docker.internal:8084"]
    metrics_path: /metrics

  - job_name: "exchange-user"
    static_configs:
      - targets: ["host.docker.internal:8085"]
    metrics_path: /metrics

  - job_name: "exchange-admin"
    static_configs:
      - targets: ["host.docker.internal:8087"]
    metrics_path: /metrics

  - job_name: "exchange-wallet"
    static_configs:
      - targets: ["host.docker.internal:8086"]
    metrics_path: /metrics
